// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAku-6vkmUbUckl9IUsDuFjyQ0wlV57HAk',
    appId: '1:762424790053:web:3e9ca005333f76a871c3cc',
    messagingSenderId: '762424790053',
    projectId: 'pet-buddy-251d5',
    authDomain: 'pet-buddy-251d5.firebaseapp.com',
    databaseURL: 'https://pet-buddy-251d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pet-buddy-251d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYXY3OFGkowExrtRR3yZjKBrKelOncXz8',
    appId: '1:762424790053:android:67f7ea66a4cd1d3471c3cc',
    messagingSenderId: '762424790053',
    projectId: 'pet-buddy-251d5',
    databaseURL: 'https://pet-buddy-251d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pet-buddy-251d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT9HuLD7ZxgaiZRFKhiHv3x_hjbgk09fs',
    appId: '1:762424790053:ios:338f0873bcfaef0e71c3cc',
    messagingSenderId: '762424790053',
    projectId: 'pet-buddy-251d5',
    databaseURL: 'https://pet-buddy-251d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pet-buddy-251d5.appspot.com',
    iosClientId: '762424790053-n7d35fbjue8eii739r7mqtlb00u34t75.apps.googleusercontent.com',
    iosBundleId: 'com.example.petBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT9HuLD7ZxgaiZRFKhiHv3x_hjbgk09fs',
    appId: '1:762424790053:ios:1326423a34dca3a771c3cc',
    messagingSenderId: '762424790053',
    projectId: 'pet-buddy-251d5',
    databaseURL: 'https://pet-buddy-251d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pet-buddy-251d5.appspot.com',
    iosClientId: '762424790053-mkrhgfsjpbis4q5tag5aqgbrfe126sh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.petBuddy.RunnerTests',
  );
}
